name: blank_project
description: A Flutter project with all the basics.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3 #state management
  go_router: ^5.0.3 # navigation
  shared_preferences: ^2.0.15 # storing data on device
  freezed: ^2.1.1 # models
  freezed_annotation: ^2.1.0 # models
  json_annotation: ^4.7.0 # models
  flutter_local_notifications: ^11.0.1 # notifications
  timezone: ^0.9.0 # notifications / init device timezone
  flutter_native_timezone: ^2.0.0 # notifications / init device timezone

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0 #models
  flutter_lints: ^2.0.0
  json_serializable: ^6.4.1 # models

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/

